spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
     ddl-auto: none
     show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

app:
  name: Spring Boot Web demo application
  version: 0.0.1
